seed: 42
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  auto_scale_batch_size: binsearch
  auto_select_gpus: true
  default_root_dir: "."
  deterministic: true
  devices: -1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gradient_clip_val: 1
  logger: true
  max_steps: 100_000
  min_steps: 1
  num_nodes: 1
  num_processes: 1
  precision: 16
  profiler: "simple"
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: true
model:
  path: bert-base-uncased
  optimizer: adamw
  lr: 1e-5
data:
  path: wikitext/wikitext-103-v1
  tokenizer: bert-base-uncased
  use_fast: true
  max_length: 512
  batch_size: 32
  num_workers: 0
  pin_memory: false
callbacks:
  rich: true
