accelerator: auto
accumulate_grad_batches: 1
auto_lr_find: true
auto_scale_batch_size: binsearch
auto_select_gpus: true
default_root_dir: "."
detect_anomaly: true
deterministic: true
devices: -1
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gradient_clip_val: 1
max_epochs: 1
min_epochs: null
max_steps: 100_000
min_steps: null
num_nodes: 1
num_processes: 1
precision: 16
profiler: simple
replace_sampler_ddp: true
strategy: null
sync_batchnorm: true
weights_summary: top
