name: Formatting
on: [push]
jobs:
  format-all:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v2

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.3.0"
      - name: ⬇️ Python Dependencies
        run: poetry install
      - name: 🏃 autoflake
        run: poetry run autoflake -ir $(find -iname "*.py" ! -path './.venv/*') --remove-all-unused-imports
      - name: 🏃 isort
        run: poetry run isort --profile=black .
      - name: 🏃 black
        run: poetry run black .

      - name: ⬆️ Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "🤖 RenTrueWang thinks you forgot to format your code!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
